### ISSUE TITLE
"SIGILL: illegal instruction" after upgrade to 0.23.0

### ISSUE THREAD

**Issue by lukiffer** [gruntwork-io/terragrunt#1085]
After a recent upgrade from 0.21.6 to 0.23.0 (and after a period of a couple hours of it working fine), I started getting a `SIGILL` when running `terragrunt` (stack trace below). Notably running `brew reinstall terragrunt` fixes the problem temporarily.

```
terragrunt --version
SIGILL: illegal instruction
PC=0x1066490 m=0 sigcode=1

goroutine 1 [running, locked to thread]:
runtime.asyncPreempt()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/preempt_amd64.s:8 fp=0xc000257e30 sp=0xc000257e28 pc=0x1066490
vendor/golang.org/x/net/http/httpproxy.init()
	/usr/local/Cellar/go/1.14/libexec/src/vendor/golang.org/x/net/http/httpproxy/proxy.go:276 fp=0xc000257e38 sp=0xc000257e30 pc=0x14190e0
runtime.doInit(0x259e280)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5414 +0x8a fp=0xc000257e68 sp=0xc000257e38 pc=0x104370a
runtime.doInit(0x25a6900)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc000257e98 sp=0xc000257e68 pc=0x10436d7
runtime.doInit(0x25a67a0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc000257ec8 sp=0xc000257e98 pc=0x10436d7
runtime.doInit(0x25a3c00)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc000257ef8 sp=0xc000257ec8 pc=0x10436d7
runtime.doInit(0x25a3f80)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc000257f28 sp=0xc000257ef8 pc=0x10436d7
runtime.doInit(0x25a4640)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc000257f58 sp=0xc000257f28 pc=0x10436d7
runtime.doInit(0x259c960)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc000257f88 sp=0xc000257f58 pc=0x10436d7
runtime.main()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:190 +0x1ce fp=0xc000257fe0 sp=0xc000257f88 pc=0x1036c6e
runtime.goexit()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000257fe8 sp=0xc000257fe0 pc=0x1064c11

rax    0x259e280
rbx    0xa
rcx    0x0
rdx    0x259e2d0
rdi    0xc00027ea00
rsi    0x14190e0
rbp    0xc000257e58
rsp    0xc000257e28
r8     0x0
r9     0x1
r10    0xc00027e700
r11    0x0
r12    0xffffffffffffffff
r13    0x3
r14    0x2
r15    0x9
rip    0x1066490
rflags 0x10202
cs     0x2b
fs     0x0
gs     0x0
```

**Comment by lukiffer** [comment]
After some digging around, it looks like it was a [regression in go](https://github.com/golang/go/issues/37459).
