### ISSUE TITLE
Terragrunt go panic with latest docker engine

### ISSUE THREAD

**Issue by GenPage** [gruntwork-io/terragrunt#1619]
I recently updated docker engine to 20.10.5 as prompted by Docker Desktop on Mac and terragrunt is throwing segmentation violations now inside of my container. Reverting the docker-engine version seems to help resolve the issue. The panic stack changes each run.

We install terragrunt in a docker container to use for our CI with the following (redacted unrelated bits):
```docker
FROM ubuntu:18.04
...
ENV TERRAGRUNT_VERSION=0.28.14
...
...
# Install terragrunt
RUN curl -Ls https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_386 \
    -o /bin/terragrunt && chmod +x /bin/terragrunt
...
```

Terragrunt panic stack
```go
root@9182555c8305:/opt/plangrid/app# terragrunt version
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x720 pc=0x808821a]

runtime stack:
runtime.throw(0x8bd5c54, 0x2a)
        /usr/local/go/src/runtime/panic.go:1117 +0x6a
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:718 +0x23f
runtime.runqput(0x0, 0x9400380, 0x1)
        /usr/local/go/src/runtime/proc.go:5746 +0x2a
runtime.newproc.func1()
        /usr/local/go/src/runtime/proc.go:3982 +0x66
runtime.systemstack(0x80a7bf4)
        /usr/local/go/src/runtime/asm_386.s:391 +0x53
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1246

goroutine 1 [running, locked to thread]:
        goroutine running on other thread; stack unavailable
```

Sometimes it will throw:
```
fatal error: runtime·unlock: lock count
fatal error: runtime·lock: lock count
panic during panic

runtime stack:
runtime.throw(0x8bbadc0, 0x19)
        /usr/local/go/src/runtime/panic.go:1117 +0x6a
runtime.lock2(0x9448188)
        /usr/local/go/src/runtime/lock_futex.go:54 +0x1bc
runtime.lockWithRank(...)
        /usr/local/go/src/runtime/lockrank_off.go:22
runtime.lock(...)
        /usr/local/go/src/runtime/lock_futex.go:47
runtime.mDoFixup(0x14)
        /usr/local/go/src/runtime/proc.go:2163 +0x28
runtime.sysmon()
        /usr/local/go/src/runtime/proc.go:5123 +0xc2
runtime.mstart1()
        /usr/local/go/src/runtime/proc.go:1306 +0x9b
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1272 +0x55

goroutine 1 [running, locked to thread]:
        goroutine running on other thread; stack unavailable
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
```

Terraform binary runs fine
```
root@9182555c8305:/opt/plangrid/app# terraform --version
Terraform v0.14.8

Your version of Terraform is out of date! The latest version
is 0.14.9. You can update by downloading from https://www.terraform.io/downloads.html
```

I know there isn't a lot pointing to the binary itself but I find it odd that the only change is docker-engine.

**Comment by GenPage** [comment]
So uh, I just realized reading the dockerfile that some previous employee was installing the 386 binary instead of amd64. Changing to use the amd64 binary fixed the issue. Sorry for the false report.
