### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by archenroot** [gruntwork-io/terragrunt#1873]
After adoption of your sample infra project from github which is cool work I started migrating it for GCP usage, but ended up in following situation:
```
[11:47:18] zangetsu@zeus  $           /data/proj/prokyon-systems/auto-accountant/infra/non-prod   master  terragrunt run-all plan && terragrunt run-all apply
INFO[0000] Stack at /data/proj/prokyon-systems/auto-accountant/infra/non-prod:
  => Module /data/proj/prokyon-systems/auto-accountant/infra/non-prod/europe-central/dev/cloud-run (excluded: false, dependencies: [])
  => Module /data/proj/prokyon-systems/auto-accountant/infra/non-prod/europe-central/dev/storage-bucket (excluded: false, dependencies: []) 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xeb5dd8]

goroutine 60 [running]:
github.com/gruntwork-io/terragrunt/config.ParseConfigString({0xc000532e00, 0x656}, 0xc00067e030, 0x0, {0xc0000543f0, 0x65}, 0x0)
        github.com/gruntwork-io/terragrunt/config/config.go:650 +0x278
github.com/gruntwork-io/terragrunt/config.ParseConfigFile({0xc0000543f0, 0x65}, 0x11c7c3a, 0x119df9b, 0xc0006b1c60)
        github.com/gruntwork-io/terragrunt/config/config.go:554 +0x59
github.com/gruntwork-io/terragrunt/config.ReadTerragruntConfig(0xc00000c3c0)
        github.com/gruntwork-io/terragrunt/config/config.go:543 +0x8d
github.com/gruntwork-io/terragrunt/cli.RunTerragrunt(0xc00000c3c0)
        github.com/gruntwork-io/terragrunt/cli/cli_app.go:368 +0xbd
github.com/gruntwork-io/terragrunt/configstack.(*runningModule).runNow(0xc00014ee60)
        github.com/gruntwork-io/terragrunt/configstack/running_module.go:239 +0x118
github.com/gruntwork-io/terragrunt/configstack.(*runningModule).runModuleWhenReady(0x0, 0xc00003a480)
        github.com/gruntwork-io/terragrunt/configstack/running_module.go:202 +0x9a
github.com/gruntwork-io/terragrunt/configstack.runModules.func1(0x0)
        github.com/gruntwork-io/terragrunt/configstack/running_module.go:172 +0x58
created by github.com/gruntwork-io/terragrunt/configstack.runModules
        github.com/gruntwork-io/terragrunt/configstack/running_module.go:170 +0x95

```

**Comment by denis256** [comment]
Hi, issue looks similar to https://github.com/gruntwork-io/terragrunt/issues/1869
which version of Terragrunt is used?

**Comment by archenroot** [comment]
Gentoo ebuild for anyne interested later
```
# Copyright 2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

DESCRIPTION="A thin wrapper for Terraform"
HOMEPAGE="https://www.gruntwork.io"
SRC_URI="https://github.com/gruntwork-io/${PN%-bin}/releases/download/v${PV}/terragrunt_linux_amd64 -> ${P}.bin"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="
	dev-lang/go
"
RDEPEND="${DEPEND}"
BDEPEND=""

src_unpack() {
	mkdir -p -- "${S}"
	cp -- "${DISTDIR}/${A}" "${S}/${PN%-bin}"
}

src_compile() { :; }

src_install() {
	dobin "${S}/${PN%-bin}"
}
```

**Comment by abdullohsattorov** [comment]
Oh My God!!!
