### ISSUE TITLE
SIGSEGV: segmentation violation code

### ISSUE THREAD

**Issue by alikhil** [gruntwork-io/terragrunt#2377]
terragrunt init command failed with the following message:

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xedfd2e]


goroutine 96 [running]:

github.com/gruntwork-io/terragrunt/config.getTerragruntOutputIfAppliedElseConfiguredDefault({{0xc000c08a60, 0x8}, {0xc001747440, 0x15}, 0x0, 0x0, 0x0, 0x0, 0xc00033d860, 0x0}, ...)

	/home/circleci/project/config/dependency.go:343 +0x26e

github.com/gruntwork-io/terragrunt/config.(*Dependency).setRenderedOutputs(0xc00010d450, 0x1)

	/home/circleci/project/config/dependency.go:127 +0x11b

github.com/gruntwork-io/terragrunt/config.dependencyBlocksToCtyValue.func1()

	/home/circleci/project/config/dependency.go:285 +0x9c

golang.org/x/sync/errgroup.(*Group).Go.func1()

	/home/circleci/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67

created by golang.org/x/sync/errgroup.(*Group).Go

	/home/circleci/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92
```

The code was the following:
```
include "state" {
  path = find_in_parent_folders()
}

include "drone" {
  path = find_in_parent_folders("drone.hcl")
}

dependency "postgres" {
  config_path = "../../postgres/common"

  mock_outputs_merge_strategy_with_state = "deep_map_only"
}

inputs = {
  postgres_user     = "recsys"
  postgres_password = dependency.postgres.outputs.user_passwords.recsys
}
```

**Comment by alikhil** [comment]
After removing line with `mock_outputs_merge_strategy_with_state = "deep_map_only"` it started working.

But I thing it's better to handle empty mock_outputs block and don't panic

**Comment by denis256** [comment]
Hello,
on which version of Terragrunt does this error occur?

**Comment by alikhil** [comment]
0.39.1

**Comment by denis256** [comment]
Fix released in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.42.7
