### ISSUE TITLE
`terraform plan` crash report

### ISSUE THREAD

**Issue by chenrui333** [gruntwork-io/terragrunt#604]
I did not touch my terragrunt config, but somehow, it seems got crashed by itself when I run it today.

Below is the crash log
```
[terragrunt] 2018/11/09 20:04:30 Error with plan: [terragrunt] [<project>/aws/eks] 2018/11/09 20:04:19 Initializing remote state for the s3 backend
[terragrunt] [<project>/aws/eks] 2018/11/09 20:04:19 Running command: terraform init -backend-config=bucket=<project>.tf-states -backend-config=key=aws/eks/terraform.tfstate -backend-config=region=us-east-1 -backend-config=encrypt=true -backend-config=dynamodb_table=<project>.tf-lock-table
Initializing modules...
- module.vpc
  Found version 1.14.0 of terraform-aws-modules/vpc/aws on registry.terraform.io
  Getting source "terraform-aws-modules/vpc/aws"
- module.eks
  Found version 1.7.0 of terraform-aws-modules/eks/aws on registry.terraform.io
  Getting source "terraform-aws-modules/eks/aws"
Initializing the backend...
Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "aws" (1.43.1)...
- Downloading plugin for provider "template" (1.0.0)...
- Downloading plugin for provider "local" (1.1.0)...
- Downloading plugin for provider "null" (1.0.0)...
The following providers do not have any version constraints in configuration,
so the latest version was installed.
To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.
* provider.local: version = "~> 1.1"
* provider.null: version = "~> 1.0"
* provider.template: version = "~> 1.0"
Terraform has been successfully initialized!
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.
If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
Error: Error refreshing state: 8 error(s) occurred:
* module.eks.aws_iam_role_policy_attachment.workers_autoscaling: 1 error(s) occurred:
* module.eks.aws_iam_role_policy_attachment.workers_autoscaling: aws_iam_role_policy_attachment.workers_autoscaling: unexpected EOF
* module.eks.aws_launch_configuration.workers: 1 error(s) occurred:
* module.eks.aws_launch_configuration.workers: aws_launch_configuration.workers: unexpected EOF
* module.eks.aws_iam_role_policy_attachment.workers_AmazonEC2ContainerRegistryReadOnly: 1 error(s) occurred:
* module.eks.aws_iam_role_policy_attachment.workers_AmazonEC2ContainerRegistryReadOnly: aws_iam_role_policy_attachment.workers_AmazonEC2ContainerRegistryReadOnly: unexpected EOF
* aws_iam_role_policy_attachment.worker_node_external_dns_policy: 1 error(s) occurred:
* aws_iam_role_policy_attachment.worker_node_external_dns_policy: aws_iam_role_policy_attachment.worker_node_external_dns_policy: unexpected EOF
* module.eks.aws_iam_role_policy_attachment.workers_AmazonEKSWorkerNodePolicy: 1 error(s) occurred:
* module.eks.aws_iam_role_policy_attachment.workers_AmazonEKSWorkerNodePolicy: aws_iam_role_policy_attachment.workers_AmazonEKSWorkerNodePolicy: unexpected EOF
* module.eks.aws_security_group_rule.cluster_https_worker_ingress: 1 error(s) occurred:
* module.eks.aws_security_group_rule.cluster_https_worker_ingress: aws_security_group_rule.cluster_https_worker_ingress: unexpected EOF
* module.eks.aws_security_group_rule.workers_ingress_self: 1 error(s) occurred:
* module.eks.aws_security_group_rule.workers_ingress_self: aws_security_group_rule.workers_ingress_self: unexpected EOF
* module.eks.aws_security_group_rule.workers_egress_internet: 1 error(s) occurred:
* module.eks.aws_security_group_rule.workers_egress_internet: aws_security_group_rule.workers_egress_internet: unexpected EOF
panic: runtime error: invalid memory address or nil pointer dereference
2018-11-09T20:04:30.459Z [DEBUG] plugin.terraform-provider-aws_v1.43.1_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x235739c]
2018-11-09T20:04:30.459Z [DEBUG] plugin.terraform-provider-aws_v1.43.1_x4: 
2018-11-09T20:04:30.459Z [DEBUG] plugin.terraform-provider-aws_v1.43.1_x4: goroutine 580 [running]:
2018-11-09T20:04:30.459Z [DEBUG] plugin.terraform-provider-aws_v1.43.1_x4: github.com/terraform-providers/terraform-provider-aws/aws.findRuleMatch(0xc00054ef80, 0xc0009b34e0, 0x3, 0x3, 0x1, 0x0)
2018-11-09T20:04:30.459Z [DEBUG] plugin.terraform-provider-aws_v1.43.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_security_group_rule.go:433 +0x6c
2018-11-09T20:04:30.459Z [DEBUG] plugin.terraform-provider-aws_v1.43.1_x4: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsSecurityGroupRuleRead(0xc0005b6310, 0x2c5ea40, 0xc00022e300, 0xc0005b6310, 0x0)
2018-11-09T20:04:30.459Z [DEBUG] plugin.terraform-provider-aws_v1.43.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_security_group_rule.go:286 +0x5fd
2018-11-09T20:04:30.459Z [DEBUG] plugin.terraform-provider-aws_v1.43.1_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc0003c9ea0, 0xc000094f50, 0x2c5ea40, 0xc00022e300, 0xc00000fdd0, 0x4bfe01, 0x273d220)
2018-11-09T20:04:30.459Z [DEBUG] plugin.terraform-provider-aws_v1.43.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:352 +0x160
2018-11-09T20:04:30.459Z [DEBUG] plugin.terraform-provider-aws_v1.43.1_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc000508ee0, 0xc000094eb0, 0xc000094f50, 0xc000062700, 0xc000bb4c20, 0x7f0a45c196c0)
2018-11-09T20:04:30.459Z [DEBUG] plugin.terraform-provider-aws_v1.43.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x92
2018-11-09T20:04:30.459Z [DEBUG] plugin.terraform-provider-aws_v1.43.1_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc00058b1a0, 0xc0006bd4d0, 0xc0006bd5c0, 0x0, 0x0)
2018-11-09T20:04:30.459Z [DEBUG] plugin.terraform-provider-aws_v1.43.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:549 +0x4e
2018-11-09T20:04:30.459Z [DEBUG] plugin.terraform-provider-aws_v1.43.1_x4: reflect.Value.call(0xc00007f260, 0xc000140848, 0x13, 0x31d66b8, 0x4, 0xc0000a3f18, 0x3, 0x3, 0xc000ae38c0, 0xc000152500, ...)
2018-11-09T20:04:30.459Z [DEBUG] plugin.terraform-provider-aws_v1.43.1_x4: 	/opt/goenv/versions/1.11.1/src/reflect/value.go:447 +0x449
2018-11-09T20:04:30.459Z [DEBUG] plugin.terraform-provider-aws_v1.43.1_x4: reflect.Value.Call(0xc00007f260, 0xc000140848, 0x13, 0xc00005c718, 0x3, 0x3, 0x5d464b, 0xc00005c728, 0x1000000000001)
2018-11-09T20:04:30.459Z [DEBUG] plugin.terraform-provider-aws_v1.43.1_x4: 	/opt/goenv/versions/1.11.1/src/reflect/value.go:308 +0xa4
2018-11-09T20:04:30.459Z [DEBUG] plugin.terraform-provider-aws_v1.43.1_x4: net/rpc.(*service).call(0xc00046cac0, 0xc000094f00, 0xc00096b4b0, 0xc00096b4c0, 0xc000155180, 0xc00031c4e0, 0x273d1e0, 0xc0006bd4d0, 0x16, 0x273d220, ...)
2018-11-09T20:04:30.459Z [DEBUG] plugin.terraform-provider-aws_v1.43.1_x4: 	/opt/goenv/versions/1.11.1/src/net/rpc/server.go:384 +0x14e
2018-11-09T20:04:30.459Z [DEBUG] plugin.terraform-provider-aws_v1.43.1_x4: created by net/rpc.(*Server).ServeCodec
2018-11-09T20:04:30.459Z [DEBUG] plugin.terraform-provider-aws_v1.43.1_x4: 	/opt/goenv/versions/1.11.1/src/net/rpc/server.go:481 +0x47e
2018/11/09 20:04:30 [ERROR] root.eks: eval: *terraform.EvalRefresh, err: aws_iam_role_policy_attachment.workers_autoscaling: unexpected EOF
2018/11/09 20:04:30 [ERROR] root.eks: eval: *terraform.EvalSequence, err: aws_iam_role_policy_attachment.workers_autoscaling: unexpected EOF
2018/11/09 20:04:30 [TRACE] [walkRefresh] Exiting eval tree: module.eks.aws_iam_role_policy_attachment.workers_autoscaling
2018/11/09 20:04:30 [ERROR] root.eks: eval: *terraform.EvalRefresh, err: aws_iam_role_policy_attachment.workers_AmazonEKSWorkerNodePolicy: unexpected EOF
2018/11/09 20:04:30 [ERROR] root.eks: eval: *terraform.EvalSequence, err: aws_iam_role_policy_attachment.workers_AmazonEKSWorkerNodePolicy: unexpected EOF
2018/11/09 20:04:30 [TRACE] [walkRefresh] Exiting eval tree: module.eks.aws_iam_role_policy_attachment.workers_AmazonEKSWorkerNodePolicy
2018/11/09 20:04:30 [ERROR] root.eks: eval: *terraform.EvalRefresh, err: aws_launch_configuration.workers: unexpected EOF
2018/11/09 20:04:30 [ERROR] root.eks: eval: *terraform.EvalSequence, err: aws_launch_configuration.workers: unexpected EOF
2018/11/09 20:04:30 [TRACE] [walkRefresh] Exiting eval tree: module.eks.aws_launch_configuration.workers
2018/11/09 20:04:30 [TRACE] dag/walk: upstream errored, not walking "module.eks.aws_autoscaling_group.workers"
2018/11/09 20:04:30 [TRACE] dag/walk: upstream errored, not walking "module.eks.output.workers_asg_names"
2018/11/09 20:04:30 [ERROR] root.eks: eval: *terraform.EvalRefresh, err: aws_security_group_rule.cluster_https_worker_ingress: unexpected EOF
2018/11/09 20:04:30 [ERROR] root.eks: eval: *terraform.EvalSequence, err: aws_security_group_rule.cluster_https_worker_ingress: unexpected EOF
2018/11/09 20:04:30 [TRACE] [walkRefresh] Exiting eval tree: module.eks.aws_security_group_rule.cluster_https_worker_ingress
2018/11/09 20:04:30 [ERROR] root.eks: eval: *terraform.EvalRefresh, err: aws_iam_role_policy_attachment.workers_AmazonEC2ContainerRegistryReadOnly: unexpected EOF
2018/11/09 20:04:30 [ERROR] root.eks: eval: *terraform.EvalSequence, err: aws_iam_role_policy_attachment.workers_AmazonEC2ContainerRegistryReadOnly: unexpected EOF
2018/11/09 20:04:30 [TRACE] [walkRefresh] Exiting eval tree: module.eks.aws_iam_role_policy_attachment.workers_AmazonEC2ContainerRegistryReadOnly
2018/11/09 20:04:30 [ERROR] root: eval: *terraform.EvalRefresh, err: aws_iam_role_policy_attachment.worker_node_external_dns_policy: unexpected EOF
2018/11/09 20:04:30 [ERROR] root: eval: *terraform.EvalSequence, err: aws_iam_role_policy_attachment.worker_node_external_dns_policy: unexpected EOF
2018/11/09 20:04:30 [TRACE] [walkRefresh] Exiting eval tree: aws_iam_role_policy_attachment.worker_node_external_dns_policy
2018/11/09 20:04:30 [ERROR] root.eks: eval: *terraform.EvalRefresh, err: aws_security_group_rule.workers_ingress_self: unexpected EOF
2018/11/09 20:04:30 [ERROR] root.eks: eval: *terraform.EvalSequence, err: aws_security_group_rule.workers_ingress_self: unexpected EOF
2018/11/09 20:04:30 [TRACE] [walkRefresh] Exiting eval tree: module.eks.aws_security_group_rule.workers_ingress_self
2018/11/09 20:04:30 [ERROR] root.eks: eval: *terraform.EvalRefresh, err: aws_security_group_rule.workers_egress_internet: unexpected EOF
2018/11/09 20:04:30 [ERROR] root.eks: eval: *terraform.EvalSequence, err: aws_security_group_rule.workers_egress_internet: unexpected EOF
2018/11/09 20:04:30 [TRACE] [walkRefresh] Exiting eval tree: module.eks.aws_security_group_rule.workers_egress_internet
2018-11-09T20:04:30.464Z [DEBUG] plugin: plugin process exited: path=<project>/aws/eks/.terraform/plugins/linux_amd64/terraform-provider-aws_v1.43.1_x4
2018/11/09 20:04:30 [TRACE] dag/walk: upstream errored, not walking "module.eks.output.workers_asg_arns"
2018/11/09 20:04:30 [TRACE] dag/walk: upstream errored, not walking "provider.aws (close)"
2018/11/09 20:04:30 [TRACE] dag/walk: upstream errored, not walking "root"
2018/11/09 20:04:30 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-11-09T20:04:30.523Z [WARN ] plugin: error closing client during Kill: err="connection is shut down"
2018-11-09T20:04:30.525Z [DEBUG] plugin: plugin process exited: path=<project>/aws/eks/.terraform/plugins/linux_amd64/terraform-provider-null_v1.0.0_x4
2018-11-09T20:04:30.525Z [DEBUG] plugin: plugin process exited: path=<project>/aws/eks/.terraform/plugins/linux_amd64/terraform-provider-local_v1.1.0_x4
2018-11-09T20:04:30.525Z [DEBUG] plugin.terraform: local-exec-provisioner (internal) 2018/11/09 20:04:30 [ERR] plugin: plugin server: accept unix /tmp/plugin247165509: use of closed network connection
2018-11-09T20:04:30.525Z [DEBUG] plugin.terraform: local-exec-provisioner (internal) 2018/11/09 20:04:30 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-11-09T20:04:30.525Z [DEBUG] plugin: plugin process exited: path=<project>/aws/eks/.terraform/plugins/linux_amd64/terraform-provider-template_v1.0.0_x4
2018-11-09T20:04:30.526Z [DEBUG] plugin: plugin process exited: path=<project>/bin/terraform
```

**Comment by yorinasub17** [comment]
Hi @chenrui333 thanks for the bug report! I just ran into the same issue, and it appears that hashicorp pushed a new version of the AWS terraform provider (https://github.com/terraform-providers/terraform-provider-aws/releases), v1.43.1 and there appears to be a bug in it. I just filed an issue there and you can track it there: https://github.com/terraform-providers/terraform-provider-aws/issues/6416

Thanks!

**Comment by chenrui333** [comment]
That is good to know. Thanks for confirming it.

**Comment by brikis98** [comment]
Closing issue since the actual bug is in https://github.com/terraform-providers/terraform-provider-aws/issues/6416.
