### ISSUE TITLE
segfault in v0.17.4

### ISSUE THREAD

**Issue by stephengroat** [gruntwork-io/terragrunt#629]
running `terragrunt plan-all` from `brew` with `terraform 0.11.11`
```
[terragrunt] [*] 2018/12/27 08:25:24 Reading Terragrunt config file at ****
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1513641]

goroutine 155 [running]:
github.com/gruntwork-io/terragrunt/cli.runTerraformWithRetry(0xc000aa1600, 0x0, 0x0)
	/private/tmp/terragrunt-20181221-18379-fddas8/terragrunt-0.17.4/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:393 +0x121
github.com/gruntwork-io/terragrunt/cli.runTerraformCommandIfNoErrors(0x0, 0x0, 0xc000aa1600, 0xc000aa1600, 0x0)
	/private/tmp/terragrunt-20181221-18379-fddas8/terragrunt-0.17.4/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:386 +0x6d
github.com/gruntwork-io/terragrunt/cli.runTerragruntWithConfig(0xc000aa1600, 0xc0005a02d0, 0xc000aa1600, 0x0, 0x0)
	/private/tmp/terragrunt-20181221-18379-fddas8/terragrunt-0.17.4/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:354 +0x2b6
github.com/gruntwork-io/terragrunt/cli.runTerraformInit(0xc00011f4a0, 0xc0005a02d0, 0x0, 0x0, 0x0)
	/private/tmp/terragrunt-20181221-18379-fddas8/terragrunt-0.17.4/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:549 +0xaa
github.com/gruntwork-io/terragrunt/cli.prepareNonInitCommand(0xc00011f4a0, 0xc0005a02d0, 0xc000a1de68, 0x1)
	/private/tmp/terragrunt-20181221-18379-fddas8/terragrunt-0.17.4/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:492 +0x8b
github.com/gruntwork-io/terragrunt/cli.runTerragruntWithConfig(0xc00011f4a0, 0xc0005a02d0, 0x0, 0x0, 0x0)
	/private/tmp/terragrunt-20181221-18379-fddas8/terragrunt-0.17.4/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:344 +0x1f2
github.com/gruntwork-io/terragrunt/cli.runTerragrunt(0xc00011f4a0, 0x166e49e, 0x15)
	/private/tmp/terragrunt-20181221-18379-fddas8/terragrunt-0.17.4/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:253 +0x11a
github.com/gruntwork-io/terragrunt/configstack.(*runningModule).runNow(0xc00039fae0, 0x0, 0x0)
	/private/tmp/terragrunt-20181221-18379-fddas8/terragrunt-0.17.4/src/github.com/gruntwork-io/terragrunt/configstack/running_module.go:224 +0x16e
github.com/gruntwork-io/terragrunt/configstack.(*runningModule).runModuleWhenReady(0xc00039fae0)
	/private/tmp/terragrunt-20181221-18379-fddas8/terragrunt-0.17.4/src/github.com/gruntwork-io/terragrunt/configstack/running_module.go:187 +0x6a
github.com/gruntwork-io/terragrunt/configstack.runModules.func1(0xc00019c000, 0xc00039fae0)
	/private/tmp/terragrunt-20181221-18379-fddas8/terragrunt-0.17.4/src/github.com/gruntwork-io/terragrunt/configstack/running_module.go:157 +0x51
created by github.com/gruntwork-io/terragrunt/configstack.runModules
	/private/tmp/terragrunt-20181221-18379-fddas8/terragrunt-0.17.4/src/github.com/gruntwork-io/terragrunt/configstack/running_module.go:155 +0xe1
```
`terraform.tfvars`
```
terragrunt = {
  include = {
    path = "${find_in_parent_folders()}"
  }
}
```
to add some more context:

this occurred when there was an error refreshing the state:
```
2018/12/27 11:11:00 [DEBUG] [aws-sdk-go] {"Item":{"Digest":{"S":"d41d8cd98f00b204e9800998ecf8427e"},"LockID":{"S":"*-terraform/*-*/*/*/terraform.tfstate-md5"}}}
2018/12/27 11:11:00 [WARN] state md5 mismatch: expected 'd41d8cd98f00b204e9800998ecf8427e', got ''
Error refreshing state: state data in S3 does not have the expected content.

This may be caused by unusually long delays in S3 processing a previous state
update.  Please wait for a minute or two and try again. If this problem
persists, and neither S3 nor DynamoDB are experiencing an outage, you may need
2018/12/27 11:11:00 [DEBUG] plugin: waiting for all plugin processes to complete...
to manually verify the remote state and update the Digest value stored in the
DynamoDB table to the following value: 
```
i had to fix the state, but i'm trying to recreate the state for testing purposes

**Comment by brikis98** [comment]
Looks like this line: https://github.com/gruntwork-io/terragrunt/blob/master/cli/cli_app.go#L393. Could `out` be `nil`?

**Comment by brikis98** [comment]
BTW, if anyone sees the bug, a PR to fix this is very welcome!

**Comment by stephengroat** [comment]
cannot replicate on newer versions
